services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      ENABLE_TASKS_API: "true"
      APP_VERSION: local-compose
      COMMIT_SHA: local
      DATABASE_URL: postgresql://postgres:postgres@db:4321/tasks
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: task-manager-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    volumes:
      - postgres_data:/var/lib/posgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
